name: PCDenoiser
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - deprecated=1.2.14
  - igl=2.2.1=py39hb2cbd16_2
  - ipykernel=6.22.0=pyh025b116_0
  - matplotlib-base=3.8.2=py39hf19769e_0
  - meshplot=0.4.0=pyhd3deb0d_2
  - pyg=2.4.0=py39_torch_1.12.0_cu116
  - python=3.9.15=h4de0772_0_cpython
  - pytorch-cluster=1.6.0=py39_torch_1.12.0_cu116
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-lightning=2.1.3=pyhd8ed1ab_0
  - pytorch-scatter=2.0.9=py39_torch_1.12.0_cu116
  - pytorch-sparse=0.6.15=py39_torch_1.12.0_cu116
  - scikit-learn=1.4.0=py39h7c199eb_0
  - pip:
    - deltaconv==1.0.2
    - robust-laplacian==0.2.7