name: PCDenoiser
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=2.123=mkl
  - blas-devel=3.9.0=23_win64_mkl
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.1.0=py39ha51f57c_2
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2024.8.30=h56e8100_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py39ha55e580_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py39h2b77a98_1
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=0
  - cuda-cudart-dev=11.6.55=0
  - cuda-cuobjdump=11.6.124=0
  - cuda-cupti=11.6.124=0
  - cuda-cuxxfilt=11.6.124=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight-compute=12.4.1=0
  - cuda-nvcc=11.6.124=0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=11.6.55=0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=11.6.124=0
  - cuda-nvrtc=11.6.124=0
  - cuda-nvrtc-dev=11.6.124=0
  - cuda-nvtx=11.6.124=0
  - cuda-nvvp=12.4.127=0
  - cuda-runtime=11.6.1=0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-version=11.6=hca96458_3
  - cuda-visual-tools=11.6.1=0
  - cudatoolkit=11.6.2=h3aee862_13
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.5=py39ha51f57c_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - deprecated=1.2.14=pyh1a96a4e_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=he0c23c2_0
  - fontconfig=2.14.2=hbde0cde_0
  - fonttools=4.53.1=py39ha55e580_1
  - freetype=2.12.1=hdaf720e_2
  - fsspec=2024.9.0=pyhff2d567_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.8=pyhd8ed1ab_0
  - igl=2.2.1=py39hb2cbd16_2
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipydatawidgets=4.3.2=pyhc268e32_0
  - ipykernel=6.22.0=pyh025b116_0
  - ipython=8.18.1=pyh7428d3b_3
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hcbf5309_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=23_win64_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=23_win64_mkl
  - libcublas=11.9.2.110=0
  - libcublas-dev=11.9.2.110=0
  - libcufft=10.7.1.112=0
  - libcufft-dev=10.7.1.112=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcusolver=11.3.4.124=0
  - libcusolver-dev=11.3.4.124=0
  - libcusparse=11.7.2.124=0
  - libcusparse-dev=11.7.2.124=0
  - libdeflate=1.21=h2466b09_0
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.80.3=h7025463_2
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=23_win64_mkl
  - liblapacke=3.9.0=23_win64_mkl
  - libnpp=11.6.3.124=0
  - libnpp-dev=11.6.3.124=0
  - libnvjpeg=11.6.2.124=0
  - libnvjpeg-dev=11.6.2.124=0
  - libpng=1.6.43=h19919ed_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.46.1=h2466b09_0
  - libtiff=4.6.0=hb151862_4
  - libuv=1.48.0=hcfcfb64_0
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.12.7=h0f24e4e_4
  - libzlib=1.3.1=h2466b09_1
  - lightning-utilities=0.11.7=pyhd8ed1ab_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.5=py39ha55e580_1
  - matplotlib-base=3.8.2=py39hf19769e_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - meshplot=0.4.0=pyhd3deb0d_2
  - mkl=2024.1.0=h66d3029_694
  - mkl-devel=2024.1.0=h57928b3_694
  - mkl-include=2024.1.0=h66d3029_694
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nsight-compute=2024.1.1.4=0
  - numpy=1.26.4=py39hddb5d58_0
  - openjpeg=2.5.2=h3d672ee_0
  - openssl=3.3.2=h2466b09_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.44=h3d7b363_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py39hfa8c767_0
  - pip=24.2=pyh8b19718_1
  - platformdirs=4.3.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py39ha55e580_1
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyg=2.4.0=py39_torch_1.12.0_cu116
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.9.15=h4de0772_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.9=5_cp39
  - pythreejs=2.4.2=pyh1d7be83_0
  - pytorch=1.12.1=py3.9_cuda11.6_cudnn8_0
  - pytorch-cluster=1.6.0=py39_torch_1.12.0_cu116
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-lightning=2.1.3=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.0.9=py39_torch_1.12.0_cu116
  - pytorch-sparse=0.6.15=py39_torch_1.12.0_cu116
  - pywin32=306=py39h99910a6_2
  - pyyaml=6.0.2=py39ha55e580_1
  - pyzmq=26.2.0=py39h03e5c00_2
  - requests=2.32.3=pyhd8ed1ab_0
  - scikit-learn=1.4.0=py39h7c199eb_0
  - scipy=1.13.1=py39h1a10956_0
  - setuptools=73.0.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.13.0=hc790b64_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h5226925_1
  - torchmetrics=1.4.0.post0=pyhd8ed1ab_0
  - tornado=6.4.1=py39ha55e580_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - traittypes=0.2.1=pyh9f0ad1d_2
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h8827d51_1
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.1.0=py39ha55989b_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - vc=14.3=h8a93ad2_20
  - vc14_runtime=14.40.33810=hcc2c482_20
  - vs2015_runtime=14.40.33810=h3bf8584_20
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - wrapt=1.16.0=py39ha55e580_1
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=he1f189c_5
  - zipp=3.20.1=pyhd8ed1ab_0
  - zstandard=0.23.0=py39h9bf74da_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - deltaconv==1.0.2
      - robust-laplacian==0.2.7
prefix: C:\Users\ruben\miniconda3\envs\PCDenoiser
